### ISSUE TITLE
Uploading of Research Documents

### ISSUE THREAD

**Issue by michaelkhanda** [KilimoGuard/kilimoGuard_Backend#19]

**Comment by KEEGANTE** [comment]
### **Pests and Diseases Affecting Maize: [https://www.corsonmaize.co.nz/pests-and-diseases](url)**

**Pests Examples:**

**1. FALL ARMYWORM (FAW)**

![image](https://github.com/user-attachments/assets/755a71b6-787a-44d4-bb93-13e922aab8a2)

_Fall armyworm larvae_ 

**_EFFECT_**

The first signs of a FAW infestation are usually identified by small pinhole-like feeding marks that look like windows anywhere on the leaf but seem to be prominent around the leaf collars.  As the larvae grow, the hole size increases and to a depth that will break through to the other side of the leaf.  

Severe infestation can cause severe crop defoliation. FAW larvae attack the ear, silks and kernels which will have detrimental effects on cob development and leaf mass, ultimately reducing crop yield.

While FAW can be difficult to distinguish from the other Army Worms present in NZ maize crops (Cosmopolitan Army Worm, Tropical Army Worm), mature FAW larvae have several distinct features:

A dark head with an upside down, pale Y-shaped marking
Four raised spots shaped like a trapezium on each body segment (seen from above)
Four sports forming a square on the second-to-last body segment

**2. ARGENTINE STEM WEEVIL**

![image](https://github.com/user-attachments/assets/9d9bac2d-da85-4022-90c4-5109c5357c91)

_Pest - Argentine Stem Weevil_

**_EFFECT_**

Can be a major threat to seedling maize plants.

Larvae enter the maize shoot soon after emergence then bore towards the base of the plant and sever the growing point.

ASW feeds on pasture tillers, therefore maize crops sown into paddocks previously in pasture or with pasture weeds with a short cultivation period, are most at risk.

Visible damage includes emergence failure, wilting and collapse.

Present in all New Zealand maize growing regions.
Damage is caused by the larvae, small white legless grubs (1 to 3 mm long) which transfer from decaying grass tillers before or soon after maize crop emergence.

Damage includes emergence failure, wilting and death of plants up to V4.

Death of emerged seedlings is characterised by a small hole of the base of the stem and subsequent wilting of the whorl leaves followed by either plant death or prolific tillering.

Imidicloprid (Gaucho) provides some level of control and Clothianidin (Poncho®) usually provides an adequate control of ASW larvae, but in severe infestations significant damage may still occur.

A grass free fallow period of 2 to 3 weeks should significantly reduce the infestation load.

**3. BLACK BEETLE**

![image](https://github.com/user-attachments/assets/010c4f76-11a9-4611-adcc-7707c46ce1bc)

_Pest - Black Beetle_

**_EFFECT_**

Confined to the warmer (upper) regions of the North Island. Infestations are more severe following long term pasture, particularly paspalum or kikuyu.

Damage is characterised by signs of chewing of the roots and stem at the base of plant. Damaged plants typically show signs of wilting and either die or tiller from the base of the plant and become stunted.

Both Imidicloprid (Gaucho) and Clothianidin (Poncho®) seed treatments provide adequate levels of control of black beetle.

**4. CORN EARWORM**

![image](https://github.com/user-attachments/assets/a09e8df6-8394-4de5-a361-96fd556268e2)

**_EFFECT_**

Also known as the tomato fruitworm can cause significant damage to developing cobs by feeding on silks (during pollination) and kernels throughout the grain fill period (R1 to R5) and subsequently by fungal attack of the grain during drydown (R6 onwards). Caterpillars are variable in colour ranging from pink to green or brown, with dark, bristley, raised bumps.

Controlling corn earworm is difficult once the caterpillars have penetrated the ear, but prior to this they may be effectively controlled by application of a synthetic pyrethroid spray whilst being mindful that this will also reduce the numbers of beneficial insects present in the crop; this includes the parasitic wasps Apanteles kazak (moderately effective at controlling corn earworm) and Apanteles rufricus (controls cosmopolitan army worm).

**5. COSMOPOLITAN ARMYWORM (CAW)**

![image](https://github.com/user-attachments/assets/cc365372-e44c-4e87-b68d-e5d79ae3b138)

**_EFFECT_**

Caterpillars are usually found at or shortly before silking. CAW caterpillars graze on leaf laminae of maize and leave only the midribs in severe cases.

CAW will consume the bottom half of plants before moving to the upper parts.

Silks and seeds may also be consumed.

**6. GREASY CUTWORM**

![image](https://github.com/user-attachments/assets/61951658-6418-4937-890e-388c2d2cebfc)

_**EFFECT**_

Cutworm damage is determined by the number and growth stage of the caterpillars in relation to the crop growth stage.

The first stages of a cutworm's life is spent on the soil surface feeding on plant leaves. As the cutworm grows it begins to sever plants and consume them, this is referred to as the “cutting stage”.

The most devastating effect occurs where “cutting stage” coincides with crop emergence. Damage though is more frequently caused by caterpillars tunnelling up the maize stem after the 4-leaf stage.

**7. GREEN VEGETABLE BUG (GVB)**

![image](https://github.com/user-attachments/assets/69aeac6f-9190-482b-a875-923786c7b3af)

**_EFFECT_**

Found throughout the North Island and warmer parts of the South Island the green vegetable bug (GVB) overwinters as adults and lay eggs in early spring.

There are typically two or more generations per season and although they are not usually a major concern from a yield perspective in maize, they do cause damage when feeding on kernels by causing discolouration, shrinkage and potential entry points for infection by fungi associated with kernel rots.

There are 3 parasitoids (all wasps) in New Zealand that are known to infect GVB, as well as a few predators (e.g. starlings and german wasps).

There are no chemicals registered for use on GVB in maize.

**8. SLUGS**

![image](https://github.com/user-attachments/assets/c69c3ec6-fb55-4269-bfcd-e5eb0399c33a)

**_EFFECT_**

Slugs may damage emerging maize crops. Cavities are gouged into the seed, sometimes affecting the growing point, and early leaves often appear shredded as a result of slug feeding. Crops sown on heavy, moist soils which have a cloddy structure and direct drilled crops are most at risk.

**Comment by KEEGANTE** [comment]
### **Pests and Diseases Affecting Maize: [https://www.corsonmaize.co.nz/pests-and-diseases](https://github.com/KilimoGuard/kilimoGuard_Backend/issues/url)**

**Diseases Examples:**

**1. ASPERGILLUS EAR ROT**

![image](https://github.com/user-attachments/assets/13b9b1be-101b-47a7-bdc4-0bf4fb1d25c2)

_**EFFECT**_

**Symptoms:** Olive-green coloured powdery mould on the base or tip of infected ears.
**Toxin type:** Aflatoxin

**2. COMMON SMUT**

![image](https://github.com/user-attachments/assets/98598858-1695-41e0-bfa6-17380936ac9a)

_**EFFECT**_

**Symptoms:** Galls form on ears, leaves, stalks and/or tassels of infected plants.
**Toxin type:** N/A

**3. DIPLODIA EAR ROT**

![image](https://github.com/user-attachments/assets/d28d8974-f45f-4d20-af6f-d85eff202d84)

**_EFFECT_**

**Symptoms:** Grey to greyish-brown mould often starting at the base of the ear spreading to cover much of the infected ears. Infected ears appear mummified and weight is severely reduced.
**Toxin type:** N/A

**4. FUSARIUM EAR ROT**

![image](https://github.com/user-attachments/assets/e85ed1ab-991a-44f9-9ec8-bf35ce693bdb)

**_EFFECT_**

**Symptoms:** White, grey or pink coloured fungal growth on individual kernels or patches of kernels in infected ears.
**Toxin type:** Fumonisin

**5. FUSARIUM HEAD BLIGHT**

![image](https://github.com/user-attachments/assets/9862bcd6-535d-4841-ae9f-71be3fa534cf)

**_EFFECT_**

Caused by a number of Fusarium species, with the disease occurring on crop residues and spreading to the growing plant. Symptoms appear after flowering and infects the cob via the silks, forming a mycelium sheath starting at the apex of the ear and progressing downwards. The decomposing kernels and the mycelium produce a characteristic pinky-brown colouring. Often an attack can occur opportunistically, following corn earworm damage or similar. There is potentially some varietal resistance, but management of previous crop residue is the key to control.

**6. GIBBERELLA EAR ROT**

![image](https://github.com/user-attachments/assets/8cc8a821-dc10-4404-abee-f4e4d0d54466)

**_EFFECT_**

**Symptoms:** White to salmon/pink mould starting at the tips of ears, with husks tightly adhering to infected ears.
**Toxin type:** Deoxynivalenol and Zearalenone

**7. HEAD SMUT**

![image](https://github.com/user-attachments/assets/b750ad3a-82dd-42d3-904b-93905d0f456d)

**_EFFECT_**

Head smut can cause serious yield losses. The cobs and tassels are invaded by spores, taking over the zone of the kernels and stamens. It is more prevalent in low-lying valleys or on land prone to flooding and in sandy or silty soils. Affected cobs are bulbous, soft and with no visible silks. The fungus gets into the plant through the mesocotyl and roots before the 8-leaf stage and spreads systemically, going up to the developing cob and tassel. Cold temperatures will slow the rate of germination and establishment of the pathogen, which survives in heat. Disease development is helped by any factor that slows early growth, for example, early dry conditions or compacted soil.

Protection is in the form of hybrid resistance and fungicidal seed treatment. Seed crops are monitored carefully to ensure no carry-over of infection.

**8. PENICILLIUM EAR ROT**

![image](https://github.com/user-attachments/assets/472d40c9-91f2-47e6-867d-c57d3d39e6e6)

_**EFFECT**_

**Symptoms:** Blue-green powdery mould on and between the kernels, usually near the tip of infected ears.
**Toxin type:** N/A

**9. TRICHODERMA EAR ROT**

![image](https://github.com/user-attachments/assets/39962078-99ca-4131-bb94-baacfaf26eee)

_**EFFECT**_

**Symptoms:** Dark-green fuzzy mould grows on and between the kernels of infected ears.
**Toxin type:** N/A

**10. COMMON RUST**

![image](https://github.com/user-attachments/assets/4aceedb2-1b38-49d4-9ffd-23a474a4ef1c)

**_EFFECT_**

Raised, rust coloured pustules appear on both sides of the leaf blade.

Chlorosis and leaf death may occur in severe infections on susceptible hybrids.

The disease favours humid conditions and moderate temperatures (15 to 25°C), including dewy nights/mornings and overwinters on host oxalis species.

**11. EYESPOT**

![image](https://github.com/user-attachments/assets/ea33f2df-c129-4eaa-b748-0de7bd9adb5b)

**_EFFECT_**

Eyespot appears as a large number of small circular spots, usually less than 4 mm in diameter and often just confined to the leaves.

Eyespot is cream to grey coloured in the centre, with a purply -brown edge and surrounded by a translucent halo when seen against the light. Initial symptoms can appear at the seedling stage and spread to the lower leaves; but the disease does not become fully established until after flowering, when it attacks the leaves above the cob. Leaf loss is the result, with severe infection causing kernels to shrivel.

Lower summer temperatures and leaf surface moisture help the disease to manifest itself, with several hours of leaf moisture required for the disease to spread. The fungus survives easily on crop residues, so it is important to bury the trash if the disease is present in a mono-crop situation.

**12. NORTHERN LEAF BLIGHT**

![image](https://github.com/user-attachments/assets/3547f3c2-ff46-4a28-a14f-244bc390d395)

**_EFFECT_**

Leaf blight is an endemic leaf disease, with visible symptoms in the form of large spindle-shaped lesions, running in the direction of the veins and causing premature drying of the leaves. In damp weather, dark brown fructifications develop, causing the disease to spread, with airborne spores infecting the upper leaves. The impact on the crop occurs through the loss of leaf area for photosynthesis and can happen rapidly – 5-12 days from initial infection to visible symptoms.

NLB is often restricted to certain specific regions of New Zealand due to the occurrence of the required climatic conditions. Risk is increased with the following factors: planting in a known hotspot, planting in a paddock subject to a previous outbreak or in close proximity to one, and close to a grain dumping site or a grain storage facility.

Control is helped by hybrid selection and shredding/mulching of previous crop residues.

**13. ROOT NECROSIS**

![image](https://github.com/user-attachments/assets/d1132409-222a-4adc-acdf-0ca2a792cdb1)

**_EFFECT_**

_Rhizoctonia/Fusarium_ - Root rot diseases are caused by a number of different pathogenic fungi affecting the roots. Rhizoctonia affects main and brace roots, causing severe necrosis with a blackening of the affected areas. Fusarium fungi causes rotting with a characteristic browning of the roots. Visible effects in the crop are often seen during early grain fill with leaves turning to green-grey, then to pink before drying out. The plant is weak, easy to pull out and therefore prone to lodging.

Higher risk situations are: sandy soils, irrigated land and in single-crop conditions where there are soil structure problems.

**14. ANTHRACNOSE STALK ROT**

![image](https://github.com/user-attachments/assets/a49bfcf5-565f-46a4-8b98-60070446d3a7)

**_EFFECT_**

Shiny, black discoloration that cannot be scratched off the rind.

**15. BACTERIAL STALK ROT**

![image](https://github.com/user-attachments/assets/db815f5d-73e5-4556-9013-fe15b39edd43)

**_EFFECT_**

Dark brown water soaked lesions at base of stem with soft, slim stalk tissues accompanied by a strong odour.

**16. CHARCOAL ROT**

![image](https://github.com/user-attachments/assets/d74b6344-c97f-47fb-a115-68b28c3bc33f)

**_EFFECT_**

Tiny, black sclerotia produced inside the stalk gives the appearance of charcoal dust.

**17. DIPLODIA STALK ROT**

![image](https://github.com/user-attachments/assets/3e21b715-f2e3-4d2a-a9e3-659298409332)

_**EFFECT**_

Tiny, raised black dots (pycnidia) on lower nodes are embedded in the stalk and cannot be scraped off.

**18. FUSARIUM STALK ROT**

![image](https://github.com/user-attachments/assets/57dbf27e-38aa-430a-b4d3-cdfb3351fc51)

**_EFFECT_**

Pinkish-white fungal growth on outside of stalk, pink or salmon colored discoloration on inside of stalk, lack of visible reproductive structures, crowns often are brown and rotted.

**19. GIBBERELLA STALK ROT**

![image](https://github.com/user-attachments/assets/87058090-aee0-404d-beec-fa35acaf4c64)

**_EFFECT_**

Bright pink to red discoloration at the nodes.

**Comment by KEEGANTE** [comment]
### **Maize Growing in Ethiopia**

**Overview**
According to (n.a., 2023) Maize is one of the most important cereal crops in Ethiopia, playing a crucial role in food security and the national economy. Ethiopia is among the top producers of maize in Africa, with maize being a staple food for a significant portion of the population. The crop is grown widely across various regions, particularly in the highland and mid-altitude areas.

**Production and Scale**
•	Significance: Maize is the second most important cereal crop in Ethiopia after teff, both in terms of production volume and area cultivated. It is grown by millions of smallholder farmers.
•	Production Areas: Major maize-growing regions include Oromia, Amhara, and the Southern Nations, Nationalities, and Peoples' Region (SNNPR). These areas have favorable agro-ecological conditions for maize production.
•	Yield: The average maize yield in Ethiopia has been increasing due to the adoption of improved seed varieties and better farming practices. However, yields are still below the potential due to various challenges.
Competition
•	Domestic Market: The maize market in Ethiopia is highly competitive, with many smallholder farmers supplying the domestic market. The crop is used for food, animal feed, and as a raw material in the agro-processing industry.
•	Regional Trade: Ethiopia competes with other East African countries like Kenya, Tanzania, and Uganda, which are also significant maize producers. Regional trade agreements and cross-border trade are important factors in the maize market.

**Pests and Diseases**
Several pests and diseases affect maize production in Ethiopia. Timely identification and management are crucial to ensure good yields:

**1.	Fall Armyworm (Spodoptera frugiperda):**
o	Impact: This invasive pest has become a major threat to maize production in Ethiopia since its introduction in 2017. It can cause severe damage to maize crops, leading to significant yield losses.
o	Management: Early detection and the use of integrated pest management strategies, including biological control, chemical pesticides, and resistant maize varieties, are recommended.

**2.	Maize Lethal Necrosis (MLN):**
o	Impact: MLN is a viral disease that affects maize and can lead to total crop loss if not managed properly. It is transmitted by insect vectors such as thrips and aphids.
o	Management: The use of virus-free seeds, crop rotation, and controlling insect vectors are key to managing MLN.

**3.	Stem Borers (Busseola fusca and Chilo partellus):**
o	Impact: Stem borers are common pests that bore into maize stems, causing physical damage and reducing yield. They are widespread in many maize-growing areas.
o	Management: Farmers can use resistant varieties, apply biological controls like parasitoids, and practice crop rotation to reduce infestation.

**4.	Gray Leaf Spot (Cercospora zeae-maydis):**
o	Impact: This fungal disease causes lesions on maize leaves, reducing photosynthetic capacity and leading to lower yields.
o	Management: Planting resistant varieties, practicing crop rotation, and applying fungicides can help manage gray leaf spot.

**5.	Maize Streak Virus (MSV):**
o	Impact: MSV is a viral disease spread by leafhoppers. It causes chlorotic streaks on maize leaves and can severely reduce yield.
o	Management: Control of leafhopper vectors and the use of resistant maize varieties are effective measures against MSV. (Pinner, 2024)

**Conclusion**
Maize growing in Ethiopia is significant both for food security and as an economic activity. However, competition is intense due to the large number of smallholder farmers and the presence of regional competitors. Pests and diseases like Fall Armyworm and Maize Lethal Necrosis are critical challenges that need to be addressed through integrated pest management, improved farming practices, and the adoption of resistant crop varieties.


**Works Cited**
n.a. (2023, 10 18). Ethiopian Institute of Agricultural Research (EIAR). Retrieved from CIMMYT: https://www.cimmyt.org/funder_partner/ethiopian-institute-of-agricultural-research-eiar/
Pinner, M. S. (2024). DSpace. Retrieved from Cimmyt.org: https://repository.cimmyt.org/home

**Comment by KEEGANTE** [comment]
### **Conditions for growing maize**
![image](https://github.com/user-attachments/assets/8ce3d849-0520-4021-83c5-9a7f2b722024)

Maize is a versatile crop that can be grown in a wide range of environments. However, optimal growth requires specific conditions to ensure good yields. Here are the general conditions for growing maize:

1. **Climate**
•	Temperature: Maize thrives in warm weather. The ideal temperature range for maize growth is between 18°C and 27°C (64°F to 81°F). Temperatures below 10°C (50°F) can slow down growth, while temperatures above 30°C (86°F) can cause heat stress and reduce yields.
•	Frost: Maize is highly sensitive to frost at any growth stage, so it should be planted after the last frost in spring and harvested before the first frost in fall.
•	Rainfall: Maize requires moderate to high rainfall, typically between 500 mm and 800 mm (20 to 31 inches) during the growing season. Rainfall should be well-distributed, especially during the critical growth stages like germination, flowering, and grain filling.

2. **Soil**
•	Soil Type: Maize grows best in well-drained, fertile loamy or sandy loam soils with good organic matter content. The soil should have good moisture retention capacity but not be prone to waterlogging.
•	pH Level: The optimal soil pH for maize is between 5.8 and 7.0. Soil that is too acidic (below pH 5.5) or too alkaline (above pH 8.0) can negatively affect nutrient availability and maize growth.
•	Soil Fertility: Maize is a heavy feeder and requires soils rich in nitrogen, phosphorus, and potassium. Regular soil testing and the use of fertilizers or organic manure are essential to maintain soil fertility.

3. **Sunlight**
•	Sunlight Exposure: Maize is a photosensitive crop that requires full sun to thrive. It needs at least 6-8 hours of direct sunlight each day. Insufficient sunlight can lead to poor growth, lower yields, and delayed maturity.

4. Planting **Time**
•	Timing: Maize should be planted when soil temperatures are consistently above 10°C (50°F) and the risk of frost has passed. In temperate regions, this typically means planting in late spring. In tropical regions, maize can be planted at the onset of the rainy season.
•	Seed Rate and Spacing: Optimal plant density is important for maximizing yield. Seeds are usually sown at a depth of 2-5 cm (0.8-2 inches) and spaced 20-30 cm (8-12 inches) apart within rows, with rows spaced 60-75 cm (24-30 inches) apart.

5. **Water Management**
•	Irrigation: In areas with insufficient rainfall, supplementary irrigation is necessary, particularly during critical stages such as tasseling, silking, and grain filling. Overwatering should be avoided as it can lead to water-logging and root diseases.

6. **Weed, Pest, and Disease Control**
•	Weed Control: Maize is vulnerable to weed competition, especially in the early growth stages. Regular weeding or the use of herbicides is essential to minimize competition for nutrients, water, and light.
•	Pest Management: Common maize pests include stem borers, armyworms, and aphids. Integrated Pest Management (IPM) practices should be employed to manage these pests effectively.
•	Disease Management: Diseases such as maize streak virus, rust, and blight can affect maize. Selecting resistant varieties and practicing crop rotation can help reduce disease incidence.

7. **Harvesting**
•	Harvesting Time: Maize is typically harvested when the grains have reached physiological maturity and the moisture content of the kernels is around 20-25%. This stage is usually indicated by the black layer formation at the base of the kernels.
•	Drying: Post-harvest drying is essential to reduce the moisture content of maize grains to around 12-14% for safe storage.
These conditions are critical for successful maize cultivation, and understanding them can help optimize production and ensure good yields.
